arguments:
  parameters:
    - name: application-name-dev
      value: atlastestapp-dev
    - name: revision
      value: main
    - name: argocd-server-address
      value: 192.168.64.18:30105
    - name: argocd-credentials-secret
      value: argocd-user
