metadata:
  generateName: deploy-testapp-
  namespace: argo
  labels:
   clusterName: hubcluster1
spec:
  entrypoint: starter
  templates:
  - name: starter
    steps:
    - - name: create-and-verify-pr
        templateRef:
          name: githubpr
          template: pr
    - - name: deploy-to-dev
        templateRef:
          name: argocdstep
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: application-name
            value: "{{workflow.parameters.application-name-dev}}"
          - name: revision
            value: "{{workflow.parameters.revision}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.argocd-server-address}}"
    - - name: deploy-to-staging
        templateRef:
          name: argocdstep
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: application-name
            value: "{{workflow.parameters.application-name-stag}}"
          - name: revision
            value: "{{workflow.parameters.revision}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.argocd-server-address}}"
